/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package electrodomesticos;

/**
 *
 * @author Manuel Manzano López
 */
public class main extends javax.swing.JFrame {
    boolean estado1,estado2,estado3;

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaconsumo = new javax.swing.JTextArea();
        jButtonbombilla = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCheckBoxestadobombilla = new javax.swing.JCheckBox();
        jButtonplancha = new javax.swing.JButton();
        jCheckBoxestadoplancha = new javax.swing.JCheckBox();
        jButtonradiador = new javax.swing.JButton();
        jCheckBoxestadoradiador = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreaconsumo.setColumns(20);
        jTextAreaconsumo.setRows(5);
        jScrollPane1.setViewportView(jTextAreaconsumo);

        jButtonbombilla.setText("Bombilla");
        jButtonbombilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbombillaActionPerformed(evt);
            }
        });

        jLabel1.setText("Consumo:");

        jCheckBoxestadobombilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxestadobombillaActionPerformed(evt);
            }
        });

        jButtonplancha.setText("Plancha");
        jButtonplancha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonplanchaActionPerformed(evt);
            }
        });

        jCheckBoxestadoplancha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxestadoplanchaActionPerformed(evt);
            }
        });

        jButtonradiador.setText("Radiador");
        jButtonradiador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonradiadorActionPerformed(evt);
            }
        });

        jCheckBoxestadoradiador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxestadoradiadorActionPerformed(evt);
            }
        });

        jButton1.setText("Consumo Total");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonbombilla)
                            .addComponent(jCheckBoxestadobombilla)
                            .addComponent(jButtonplancha)
                            .addComponent(jCheckBoxestadoplancha)
                            .addComponent(jButtonradiador)
                            .addComponent(jCheckBoxestadoradiador)
                            .addComponent(jButton1)))
                    .addComponent(jLabel1))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonbombilla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxestadobombilla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonplancha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxestadoplancha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonradiador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxestadoradiador)
                        .addGap(33, 33, 33)
                        .addComponent(jButton1)
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonbombillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbombillaActionPerformed
        
        Aparato bombilla= new Aparato("Bombilla",100);
        if(!bombilla.isEstado()){
            jCheckBoxestadobombilla.setText("Apagado");
            jCheckBoxestadobombilla.setSelected(false);
        }else{
            jCheckBoxestadobombilla.setText("Encendido");
            jCheckBoxestadobombilla.setSelected(true);
        }
        jTextAreaconsumo.append(bombilla.toString()+"\n");
        estado1=bombilla.isEstado();
        
    }//GEN-LAST:event_jButtonbombillaActionPerformed

    private void jButtonplanchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonplanchaActionPerformed
      
        Aparato plancha = new Aparato("Plancha", 1200);
        if(!plancha.isEstado()){
            jCheckBoxestadoplancha.setText("Apagado");
            jCheckBoxestadoplancha.setSelected(false);
            
        }else{
            jCheckBoxestadoplancha.setText("Encendido");
            jCheckBoxestadoplancha.setSelected(true);
        }
        jTextAreaconsumo.append(plancha.toString()+"\n");
        estado1=plancha.isEstado();
        
    }//GEN-LAST:event_jButtonplanchaActionPerformed

    private void jButtonradiadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonradiadorActionPerformed
        
        Aparato radiador = new Aparato ("Radiador",2000);
        if(!radiador.isEstado()){
            jCheckBoxestadoradiador.setText("Apagado");
            jCheckBoxestadoradiador.setSelected(false);
        }else{
            jCheckBoxestadoradiador.setText("Encendido");
            jCheckBoxestadoradiador.setSelected(true);
        }
        jTextAreaconsumo.append(radiador.toString()+"\n");
        estado1=radiador.isEstado();
        
    }//GEN-LAST:event_jButtonradiadorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        jTextAreaconsumo.append("El consumo Actual es :"+Aparato.getConsumoTotal()+"\n");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBoxestadobombillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxestadobombillaActionPerformed
        
        estado1=jCheckBoxestadobombilla.isSelected();
        if(jCheckBoxestadobombilla.isSelected()){
            jCheckBoxestadobombilla.setText("Encendido");
            
        }else{
            jCheckBoxestadobombilla.setText("Apagado");
        }
       
    }//GEN-LAST:event_jCheckBoxestadobombillaActionPerformed

    private void jCheckBoxestadoplanchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxestadoplanchaActionPerformed
        estado2=jCheckBoxestadoplancha.isSelected();
        if(jCheckBoxestadoplancha.isSelected()){
            jCheckBoxestadoplancha.setText("Encendido");
        }else{
            jCheckBoxestadoplancha.setText("Apagado");
        }
        
    }//GEN-LAST:event_jCheckBoxestadoplanchaActionPerformed

    private void jCheckBoxestadoradiadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxestadoradiadorActionPerformed
        estado3=jCheckBoxestadoradiador.isSelected();
       if(jCheckBoxestadoradiador.isSelected()){
            jCheckBoxestadoradiador.setText("Encendido");
            
        }else{
            jCheckBoxestadoradiador.setText("Apagado");
        }
    }//GEN-LAST:event_jCheckBoxestadoradiadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonbombilla;
    private javax.swing.JButton jButtonplancha;
    private javax.swing.JButton jButtonradiador;
    private javax.swing.JCheckBox jCheckBoxestadobombilla;
    private javax.swing.JCheckBox jCheckBoxestadoplancha;
    private javax.swing.JCheckBox jCheckBoxestadoradiador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaconsumo;
    // End of variables declaration//GEN-END:variables
}
