/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semaforo;

import java.awt.Color;

/**
 *
 * @author Manuel Manzano López
 */
public class main extends javax.swing.JFrame {
    Color defecto = new Color(255, 255, 255);
    Semaforo semaforo1 = new Semaforo();
    
    
    

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelrojo = new javax.swing.JLabel();
        jButtonbajar = new javax.swing.JButton();
        jLabelverde = new javax.swing.JLabel();
        jLabelambar = new javax.swing.JLabel();
        jButtonsubir = new javax.swing.JButton();
        jCheckBoxparpadea = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelrojo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonbajar.setText("Subir");
        jButtonbajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbajarActionPerformed(evt);
            }
        });

        jLabelverde.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelambar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonsubir.setText("Bajar");
        jButtonsubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsubirActionPerformed(evt);
            }
        });

        jCheckBoxparpadea.setText("Parpadea");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelambar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelverde, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelrojo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonbajar)
                            .addComponent(jButtonsubir)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxparpadea)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelrojo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelambar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jLabelverde, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jCheckBoxparpadea)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonbajar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonsubir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonsubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsubirActionPerformed
        
        jLabelrojo.setBackground(defecto);
        jLabelambar.setBackground(defecto);
        jLabelverde.setBackground(defecto);
        
        semaforo1.subir();
        
        switch (semaforo1.getEstado()){
            case 0:
                jLabelrojo.setBackground(Color.RED);
                jCheckBoxparpadea.setSelected(semaforo1.isparpadenado());
                break;
            case 1:
                jLabelambar.setBackground(Color.ORANGE);
                jCheckBoxparpadea.setSelected(semaforo1.isparpadenado());
                break;
            case 2:
                jLabelverde.setBackground(Color.GREEN);
                jCheckBoxparpadea.setSelected(semaforo1.isparpadenado());
                break;
                    
        }
        
    }//GEN-LAST:event_jButtonsubirActionPerformed

    private void jButtonbajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbajarActionPerformed
        
        jLabelrojo.setBackground(defecto);
        jLabelambar.setBackground(defecto);
        jLabelverde.setBackground(defecto);
        
        semaforo1.bajar();
        
        switch (semaforo1.getEstado()){
            case 0:
                jLabelrojo.setBackground(Color.RED);
                jCheckBoxparpadea.setSelected(semaforo1.isparpadenado());
                break;
            case 1:
                jLabelambar.setBackground(Color.ORANGE);
                jCheckBoxparpadea.setSelected(semaforo1.isparpadenado());
                break;
            case 2:
                jLabelverde.setBackground(Color.GREEN);
                jCheckBoxparpadea.setSelected(semaforo1.isparpadenado());
                break;
                    
        }
    }//GEN-LAST:event_jButtonbajarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new main().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonbajar;
    private javax.swing.JButton jButtonsubir;
    private javax.swing.JCheckBox jCheckBoxparpadea;
    private javax.swing.JLabel jLabelambar;
    private javax.swing.JLabel jLabelrojo;
    private javax.swing.JLabel jLabelverde;
    // End of variables declaration//GEN-END:variables
}
