/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegopiedrapapeltijeras;

import java.awt.Dialog;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Manuel Manzano López.
 */
public class main extends javax.swing.JFrame {

    private static final Logger LOG = Logger.getLogger(main.class.getName());
    int symbols = RockScissorsPaper.symbols;
    String name = RockScissorsPaper.namegamer;
    int trys = symbols;
    static int theme = 0;
    final ImageIcon ROCK = new ImageIcon(getClass().getResource("../Imagenes/rock.png"));
    final ImageIcon PAPER = new ImageIcon(getClass().getResource("../Imagenes/paper.png"));
    final ImageIcon SCISSORS = new ImageIcon(getClass().getResource("../Imagenes/scissors.png"));
    final ImageIcon LIZARD = new ImageIcon(getClass().getResource("../Imagenes/lizard.png"));
    final ImageIcon SPOCK = new ImageIcon(getClass().getResource("../Imagenes/Spock.png"));
    final ImageIcon DEFAULT = new ImageIcon(getClass().getResource("../Imagenes/default.png"));
    final ImageIcon THEME = DEFAULT;
    final ImageIcon THEME1 = new ImageIcon(getClass().getResource("../Imagenes/Tema1.jpg"));
    final ImageIcon THEME2 = new ImageIcon(getClass().getResource("../Imagenes/Tema2.jpg"));
    final ImageIcon THEME3 = new ImageIcon(getClass().getResource("../Imagenes/Tema3.jpg"));
    final ImageIcon THEME4 = new ImageIcon(getClass().getResource("../Imagenes/Tema4.jpg"));
    final ImageIcon THEME5 = new ImageIcon(getClass().getResource("../Imagenes/Tema5.png"));

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../Imagenes/rock-paper-scissors.png")).getImage());
        this.setModalExclusionType(Dialog.ModalExclusionType.NO_EXCLUDE);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        jDialogstart.setModal(true);
        jDialogname.setModal(true);
        jDialogColor.setModal(true);
        jDialogstart.setLocationRelativeTo(this);
        jDialogname.setLocationRelativeTo(jDialogstart);
        jDialogColor.setLocationRelativeTo(jDialogstart);
        jDialogsettings.setLocationRelativeTo(this);
        jDialogsettings.setModal(true);
        jDialogsettings.setLocationByPlatform(false);
        jTextFieldname.setText(RockScissorsPaper.namegamer);
        jPanelcolorgame.setBackground(RockScissorsPaper.gamercolor);
        jRadioButtontheme1.setSelected(true);
        jSlidertrys.setValue(RockScissorsPaper.numround);
        jTextFieldtrys.setText(String.valueOf(RockScissorsPaper.numround));
        jDialogstart.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogstart = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jButtoncolor = new javax.swing.JButton();
        jPanelcolorgame = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButtonnombre = new javax.swing.JButton();
        jCheckBoxthreesymbols = new javax.swing.JCheckBox();
        jCheckBoxfivesymbols = new javax.swing.JCheckBox();
        jButtonaceptstart = new javax.swing.JButton();
        jDialogname = new javax.swing.JDialog();
        jButtonaceptname = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldname = new javax.swing.JTextField();
        jDialogColor = new javax.swing.JDialog();
        jColorChooser1 = new javax.swing.JColorChooser();
        jButtonaceptcolor = new javax.swing.JButton();
        buttonGroupsymbols = new javax.swing.ButtonGroup();
        jDialogsettings = new javax.swing.JDialog();
        jButtonacepsetting = new javax.swing.JButton();
        jTabbedPanesetting = new javax.swing.JTabbedPane();
        jPanelparameter = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jSlidertrys = new javax.swing.JSlider();
        jTextFieldtrys = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanelcustomize = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jRadioButtontheme1 = new javax.swing.JRadioButton();
        jRadioButtontheme2 = new javax.swing.JRadioButton();
        jRadioButtontheme3 = new javax.swing.JRadioButton();
        jRadioButtontheme4 = new javax.swing.JRadioButton();
        jRadioButtontheme5 = new javax.swing.JRadioButton();
        jRadioButtontheme6 = new javax.swing.JRadioButton();
        jButtoncolor1 = new javax.swing.JButton();
        jPanelcolor = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButtonname = new javax.swing.JButton();
        jLabelname = new javax.swing.JLabel();
        jPanellanguage = new javax.swing.JPanel();
        jRadioButtonspanish = new javax.swing.JRadioButton();
        jRadioButtonenglish = new javax.swing.JRadioButton();
        jRadioButtonfrench = new javax.swing.JRadioButton();
        jRadioButtondeutch = new javax.swing.JRadioButton();
        jButtoncancelsetting = new javax.swing.JButton();
        buttonGrouptheme = new javax.swing.ButtonGroup();
        buttonGrouplanguaje = new javax.swing.ButtonGroup();
        jButtongame = new javax.swing.JButton();
        jPaneljugador = new javax.swing.JPanel();
        jLabelchoiceimagegamer = new javax.swing.JLabel();
        jPanelcomputadora = new javax.swing.JPanel();
        jLabelchoiceimagePC = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelnamegamer = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldscoregamer = new javax.swing.JTextField();
        jTextFieldscorepc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelselection = new javax.swing.JLabel();
        jSliderchoicegamer = new javax.swing.JSlider();
        jLabeltheme = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemnewplay = new javax.swing.JMenuItem();
        jMenuItemresume = new javax.swing.JMenuItem();
        jMenuItemexit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemsetting = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jDialogstart.setMinimumSize(new java.awt.Dimension(450, 350));
        jDialogstart.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        jDialogstart.setModalityType(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtoncolor.setText("Color");
        jButtoncolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncolorActionPerformed(evt);
            }
        });

        jPanelcolorgame.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanelcolorgameLayout = new javax.swing.GroupLayout(jPanelcolorgame);
        jPanelcolorgame.setLayout(jPanelcolorgameLayout);
        jPanelcolorgameLayout.setHorizontalGroup(
            jPanelcolorgameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelcolorgameLayout.setVerticalGroup(
            jPanelcolorgameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel7.setText("Jugador:");

        jButtonnombre.setText("Nombre");
        jButtonnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnombreActionPerformed(evt);
            }
        });

        buttonGroupsymbols.add(jCheckBoxthreesymbols);
        jCheckBoxthreesymbols.setSelected(true);
        jCheckBoxthreesymbols.setText("Piedra-Papel-Tijeras");

        buttonGroupsymbols.add(jCheckBoxfivesymbols);
        jCheckBoxfivesymbols.setText("Piedra-Papel-Tijeras-Lagarto-Spok");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelcolorgame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtoncolor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonnombre)))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxthreesymbols)
                    .addComponent(jCheckBoxfivesymbols))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtoncolor)
                    .addComponent(jButtonnombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBoxthreesymbols)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxfivesymbols))
                    .addComponent(jPanelcolorgame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButtonaceptstart.setText("Aceptar");
        jButtonaceptstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaceptstartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogstartLayout = new javax.swing.GroupLayout(jDialogstart.getContentPane());
        jDialogstart.getContentPane().setLayout(jDialogstartLayout);
        jDialogstartLayout.setHorizontalGroup(
            jDialogstartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogstartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogstartLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonaceptstart)
                .addContainerGap())
        );
        jDialogstartLayout.setVerticalGroup(
            jDialogstartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogstartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButtonaceptstart)
                .addContainerGap())
        );

        jDialogname.setMinimumSize(new java.awt.Dimension(350, 200));
        jDialogname.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        jDialogname.setModalityType(null);

        jButtonaceptname.setText("Aceptar");
        jButtonaceptname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaceptnameActionPerformed(evt);
            }
        });

        jLabel8.setText("Introduce el nombre de jugador:");

        javax.swing.GroupLayout jDialognameLayout = new javax.swing.GroupLayout(jDialogname.getContentPane());
        jDialogname.getContentPane().setLayout(jDialognameLayout);
        jDialognameLayout.setHorizontalGroup(
            jDialognameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialognameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialognameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialognameLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonaceptname))
                    .addGroup(jDialognameLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 69, Short.MAX_VALUE))
                    .addComponent(jTextFieldname))
                .addContainerGap())
        );
        jDialognameLayout.setVerticalGroup(
            jDialognameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialognameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonaceptname)
                .addContainerGap())
        );

        jDialogColor.setMinimumSize(new java.awt.Dimension(650, 550));
        jDialogColor.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        jDialogColor.setModalityType(null);

        jColorChooser1.setMinimumSize(new java.awt.Dimension(620, 400));
        jColorChooser1.setPreferredSize(new java.awt.Dimension(620, 400));

        jButtonaceptcolor.setText("Aceptar");
        jButtonaceptcolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaceptcolorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogColorLayout = new javax.swing.GroupLayout(jDialogColor.getContentPane());
        jDialogColor.getContentPane().setLayout(jDialogColorLayout);
        jDialogColorLayout.setHorizontalGroup(
            jDialogColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogColorLayout.createSequentialGroup()
                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogColorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonaceptcolor)
                .addContainerGap())
        );
        jDialogColorLayout.setVerticalGroup(
            jDialogColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogColorLayout.createSequentialGroup()
                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonaceptcolor)
                .addContainerGap())
        );

        jDialogsettings.setMinimumSize(new java.awt.Dimension(400, 400));
        jDialogsettings.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jButtonacepsetting.setText("Aceptar");
        jButtonacepsetting.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButtonacepsettingAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButtonacepsetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonacepsettingActionPerformed(evt);
            }
        });

        jLabel4.setText("Intentos:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Piedra, Papel, Tijeras", "Piedra, Papel, Tijeras, Lagarto, Spock", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jSlidertrys.setMajorTickSpacing(1);
        jSlidertrys.setMinimum(1);
        jSlidertrys.setMinorTickSpacing(1);
        jSlidertrys.setPaintTicks(true);
        jSlidertrys.setSnapToTicks(true);
        jSlidertrys.setValue(1);
        jSlidertrys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSlidertrysMouseReleased(evt);
            }
        });

        jTextFieldtrys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtrysActionPerformed(evt);
            }
        });
        jTextFieldtrys.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldtrysKeyTyped(evt);
            }
        });

        jLabel1.setText("Modo Juego:");

        javax.swing.GroupLayout jPanelparameterLayout = new javax.swing.GroupLayout(jPanelparameter);
        jPanelparameter.setLayout(jPanelparameterLayout);
        jPanelparameterLayout.setHorizontalGroup(
            jPanelparameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelparameterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelparameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelparameterLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelparameterLayout.createSequentialGroup()
                        .addGroup(jPanelparameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanelparameterLayout.createSequentialGroup()
                                .addComponent(jSlidertrys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldtrys, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(117, Short.MAX_VALUE))))
        );
        jPanelparameterLayout.setVerticalGroup(
            jPanelparameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelparameterLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelparameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlidertrys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldtrys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jTabbedPanesetting.addTab("Parámetros", jPanelparameter);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel9.setMaximumSize(new java.awt.Dimension(125, 90));
        jLabel9.setMinimumSize(new java.awt.Dimension(125, 90));
        jLabel9.setPreferredSize(new java.awt.Dimension(125, 90));

        jLabel10.setText("Default");

        jLabel11.setText("Escritorio");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Tema1.jpg"))); // NOI18N
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel12.setMaximumSize(new java.awt.Dimension(125, 90));
        jLabel12.setMinimumSize(new java.awt.Dimension(125, 90));
        jLabel12.setPreferredSize(new java.awt.Dimension(125, 90));

        jLabel13.setText("Natural");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Tema2.jpg"))); // NOI18N
        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel14.setMaximumSize(new java.awt.Dimension(125, 90));
        jLabel14.setMinimumSize(new java.awt.Dimension(125, 90));
        jLabel14.setPreferredSize(new java.awt.Dimension(125, 90));

        jLabel15.setText("Forma");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Tema3.jpg"))); // NOI18N
        jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel16.setMaximumSize(new java.awt.Dimension(125, 90));
        jLabel16.setMinimumSize(new java.awt.Dimension(125, 90));
        jLabel16.setPreferredSize(new java.awt.Dimension(125, 90));

        jLabel19.setText("Barnizado");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Tema4.jpg"))); // NOI18N
        jLabel20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel20.setMaximumSize(new java.awt.Dimension(125, 90));
        jLabel20.setMinimumSize(new java.awt.Dimension(125, 90));
        jLabel20.setPreferredSize(new java.awt.Dimension(125, 90));

        jLabel23.setText("Rústico");

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Tema5.png"))); // NOI18N
        jLabel24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel24.setMaximumSize(new java.awt.Dimension(125, 90));
        jLabel24.setMinimumSize(new java.awt.Dimension(125, 90));
        jLabel24.setPreferredSize(new java.awt.Dimension(125, 90));

        buttonGrouptheme.add(jRadioButtontheme1);
        jRadioButtontheme1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtontheme1ActionPerformed(evt);
            }
        });

        buttonGrouptheme.add(jRadioButtontheme2);
        jRadioButtontheme2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtontheme2ActionPerformed(evt);
            }
        });

        buttonGrouptheme.add(jRadioButtontheme3);
        jRadioButtontheme3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtontheme3ActionPerformed(evt);
            }
        });

        buttonGrouptheme.add(jRadioButtontheme4);
        jRadioButtontheme4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtontheme4ActionPerformed(evt);
            }
        });

        buttonGrouptheme.add(jRadioButtontheme5);
        jRadioButtontheme5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtontheme5ActionPerformed(evt);
            }
        });

        buttonGrouptheme.add(jRadioButtontheme6);
        jRadioButtontheme6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtontheme6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButtontheme1)
                                .addComponent(jRadioButtontheme2, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jRadioButtontheme3)
                            .addComponent(jRadioButtontheme4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(jRadioButtontheme5, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jRadioButtontheme6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10))
                                    .addComponent(jRadioButtontheme1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11))
                                    .addComponent(jRadioButtontheme2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13))
                            .addComponent(jRadioButtontheme3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addComponent(jRadioButtontheme4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19))
                    .addComponent(jRadioButtontheme5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23))
                    .addComponent(jRadioButtontheme6))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel9);

        jButtoncolor1.setText("Color");
        jButtoncolor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncolor1ActionPerformed(evt);
            }
        });

        jPanelcolor.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanelcolorLayout = new javax.swing.GroupLayout(jPanelcolor);
        jPanelcolor.setLayout(jPanelcolorLayout);
        jPanelcolorLayout.setHorizontalGroup(
            jPanelcolorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanelcolorLayout.setVerticalGroup(
            jPanelcolorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel17.setText("Tema:");

        jLabel18.setText("Jugador:");

        jButtonname.setText("Nombre");
        jButtonname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnameActionPerformed(evt);
            }
        });

        jLabelname.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelcustomizeLayout = new javax.swing.GroupLayout(jPanelcustomize);
        jPanelcustomize.setLayout(jPanelcustomizeLayout);
        jPanelcustomizeLayout.setHorizontalGroup(
            jPanelcustomizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelcustomizeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelcustomizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelcustomizeLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(167, 167, 167))
                    .addGroup(jPanelcustomizeLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanelcustomizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelcustomizeLayout.createSequentialGroup()
                        .addGroup(jPanelcustomizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jPanelcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelcustomizeLayout.createSequentialGroup()
                                .addComponent(jButtoncolor1)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonname)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelcustomizeLayout.setVerticalGroup(
            jPanelcustomizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelcustomizeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelcustomizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17))
                .addGap(11, 11, 11)
                .addGroup(jPanelcustomizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelcustomizeLayout.createSequentialGroup()
                        .addGroup(jPanelcustomizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtoncolor1)
                            .addComponent(jButtonname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPanesetting.addTab("Personalización", jPanelcustomize);

        buttonGrouplanguaje.add(jRadioButtonspanish);
        jRadioButtonspanish.setSelected(true);
        jRadioButtonspanish.setText("Español");

        buttonGrouplanguaje.add(jRadioButtonenglish);
        jRadioButtonenglish.setText("Ingles");

        buttonGrouplanguaje.add(jRadioButtonfrench);
        jRadioButtonfrench.setText("Frances");

        buttonGrouplanguaje.add(jRadioButtondeutch);
        jRadioButtondeutch.setText("Aleman");

        javax.swing.GroupLayout jPanellanguageLayout = new javax.swing.GroupLayout(jPanellanguage);
        jPanellanguage.setLayout(jPanellanguageLayout);
        jPanellanguageLayout.setHorizontalGroup(
            jPanellanguageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanellanguageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanellanguageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonspanish)
                    .addComponent(jRadioButtonenglish)
                    .addComponent(jRadioButtonfrench)
                    .addComponent(jRadioButtondeutch))
                .addContainerGap(316, Short.MAX_VALUE))
        );
        jPanellanguageLayout.setVerticalGroup(
            jPanellanguageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanellanguageLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jRadioButtonspanish)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonenglish)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonfrench)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtondeutch)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        jTabbedPanesetting.addTab("Idioma", jPanellanguage);

        jButtoncancelsetting.setText("Cancelar");
        jButtoncancelsetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncancelsettingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogsettingsLayout = new javax.swing.GroupLayout(jDialogsettings.getContentPane());
        jDialogsettings.getContentPane().setLayout(jDialogsettingsLayout);
        jDialogsettingsLayout.setHorizontalGroup(
            jDialogsettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogsettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogsettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPanesetting)
                    .addGroup(jDialogsettingsLayout.createSequentialGroup()
                        .addComponent(jButtonacepsetting)
                        .addGap(18, 18, 18)
                        .addComponent(jButtoncancelsetting)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jDialogsettingsLayout.setVerticalGroup(
            jDialogsettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogsettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanesetting)
                .addGap(18, 18, 18)
                .addGroup(jDialogsettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonacepsetting)
                    .addComponent(jButtoncancelsetting))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego");
        setMaximumSize(new java.awt.Dimension(550, 620));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setPreferredSize(new java.awt.Dimension(500, 620));
        getContentPane().setLayout(null);

        jButtongame.setText("Jugar");
        jButtongame.setOpaque(false);
        jButtongame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtongameActionPerformed(evt);
            }
        });
        getContentPane().add(jButtongame);
        jButtongame.setBounds(179, 494, 106, 61);

        jPaneljugador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPaneljugador.setOpaque(false);

        jLabelchoiceimagegamer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPaneljugadorLayout = new javax.swing.GroupLayout(jPaneljugador);
        jPaneljugador.setLayout(jPaneljugadorLayout);
        jPaneljugadorLayout.setHorizontalGroup(
            jPaneljugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneljugadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelchoiceimagegamer, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPaneljugadorLayout.setVerticalGroup(
            jPaneljugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneljugadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelchoiceimagegamer, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPaneljugador);
        jPaneljugador.setBounds(252, 73, 220, 272);

        jPanelcomputadora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelcomputadora.setOpaque(false);

        jLabelchoiceimagePC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelcomputadoraLayout = new javax.swing.GroupLayout(jPanelcomputadora);
        jPanelcomputadora.setLayout(jPanelcomputadoraLayout);
        jPanelcomputadoraLayout.setHorizontalGroup(
            jPanelcomputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelcomputadoraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelchoiceimagePC, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelcomputadoraLayout.setVerticalGroup(
            jPanelcomputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelcomputadoraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelchoiceimagePC, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanelcomputadora);
        jPanelcomputadora.setBounds(11, 73, 212, 272);

        jProgressBar1.setToolTipText("");
        jProgressBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(169, 42, 150, 18);

        jLabel2.setText("Progreso:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(212, 14, 80, 14);

        jLabel3.setText("PC");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(98, 351, 30, 20);

        jLabelnamegamer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelnamegamer.setToolTipText("Gamer");
        jLabelnamegamer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelnamegamer.setOpaque(true);
        getContentPane().add(jLabelnamegamer);
        jLabelnamegamer.setBounds(252, 351, 210, 14);

        jLabel5.setText("Puntuación:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(252, 377, 70, 14);

        jTextFieldscoregamer.setEditable(false);
        getContentPane().add(jTextFieldscoregamer);
        jTextFieldscoregamer.setBounds(327, 374, 140, 30);

        jTextFieldscorepc.setEditable(false);
        getContentPane().add(jTextFieldscorepc);
        jTextFieldscorepc.setBounds(86, 371, 137, 30);

        jLabel6.setText("Puntuación:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(11, 374, 70, 14);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Elección Jugador"));
        jPanel1.setOpaque(false);

        jSliderchoicegamer.setMajorTickSpacing(1);
        jSliderchoicegamer.setMinorTickSpacing(1);
        jSliderchoicegamer.setValue(0);
        jSliderchoicegamer.setOpaque(false);
        jSliderchoicegamer.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderchoicegamerMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jSliderchoicegamerMouseMoved(evt);
            }
        });
        jSliderchoicegamer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSliderchoicegamerKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelselection, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jSliderchoicegamer, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelselection, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSliderchoicegamer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(111, 412, 244, 71);
        getContentPane().add(jLabeltheme);
        jLabeltheme.setBounds(0, 0, 490, 570);

        jMenu1.setText("Archivo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItemnewplay.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemnewplay.setText("Nueva Partida");
        jMenuItemnewplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemnewplayActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemnewplay);

        jMenuItemresume.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemresume.setText("Reiniciar");
        jMenuItemresume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemresumeActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemresume);

        jMenuItemexit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemexit.setText("Salir");
        jMenuItemexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemexitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemexit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Juego");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItemsetting.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemsetting.setText("Preferencias");
        jMenuItemsetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemsettingActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemsetting);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Acerca de");
        jMenuBar1.add(jMenu4);

        jMenu3.setText("Ayuda");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemexitActionPerformed

        System.exit(0);
    }//GEN-LAST:event_jMenuItemexitActionPerformed

    private void jMenuItemresumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemresumeActionPerformed

        jDialogstart.setVisible(true);
        jDialogstart.setAlwaysOnTop(true);
        jDialogstart.setLocationRelativeTo(this);
        jDialogname.setLocationRelativeTo(jDialogstart);
        jDialogColor.setLocationRelativeTo(jDialogstart);
        RockScissorsPaper.setGameRound(trys);
        RockScissorsPaper.setDefault(RockScissorsPaper.numround);
        jProgressBar1.setValue(0);
        jLabelchoiceimagePC.setIcon(this.getImage(-1));
        jLabelchoiceimagePC.repaint();
        jLabelchoiceimagegamer.setIcon(this.getImage(-1));
        jLabelchoiceimagegamer.repaint();
        jSliderchoicegamer.setValue(0);
        jButtongame.setEnabled(true);
    }//GEN-LAST:event_jMenuItemresumeActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        jDialogsettings.setVisible(true);
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jButtoncolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncolorActionPerformed
        jDialogColor.setVisible(true);
        jDialogColor.setAlwaysOnTop(true);
        getRootPane().setDefaultButton(jButtonaceptcolor);
    }//GEN-LAST:event_jButtoncolorActionPerformed

    private void jButtonnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnombreActionPerformed
        jDialogname.setVisible(true);
        jDialogname.setAlwaysOnTop(true);
        getRootPane().setDefaultButton(jButtonaceptname);
    }//GEN-LAST:event_jButtonnombreActionPerformed

    private void jButtonaceptcolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaceptcolorActionPerformed
        juegopiedrapapeltijeras.RockScissorsPaper.setGamercolor(jColorChooser1.getColor());
        jDialogColor.setVisible(false);
        jPanelcolorgame.setBackground(jColorChooser1.getColor());
        jPanelcolor.setBackground(jColorChooser1.getColor());
        getRootPane().setDefaultButton(jButtonaceptstart);
    }//GEN-LAST:event_jButtonaceptcolorActionPerformed

    private void jButtonaceptnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaceptnameActionPerformed
        juegopiedrapapeltijeras.RockScissorsPaper.setNamegamer(jTextFieldname.getText());
        jDialogstart.setTitle(jTextFieldname.getText());
        jLabelname.setText(RockScissorsPaper.namegamer);
        this.setTitle("Game: PC Vs. " + jTextFieldname.getText());
        jDialogname.setVisible(false);
    }//GEN-LAST:event_jButtonaceptnameActionPerformed

    private void jMenuItemnewplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemnewplayActionPerformed
        RockScissorsPaper.setGameRound(trys);
        jLabelchoiceimagePC.setIcon(this.getImage(-1));
        jLabelchoiceimagePC.repaint();
        jLabelchoiceimagegamer.setIcon(this.getImage(-1));
        jLabelchoiceimagegamer.repaint();
        jSliderchoicegamer.setValue(0);
        jButtongame.setEnabled(true);
        jProgressBar1.setValue(0);
    }//GEN-LAST:event_jMenuItemnewplayActionPerformed

    private void jSliderchoicegamerMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderchoicegamerMouseMoved

        jLabelselection.setText(RockScissorsPaper.toStringvalues(jSliderchoicegamer.getValue()));

    }//GEN-LAST:event_jSliderchoicegamerMouseMoved

    private void jButtonaceptstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaceptstartActionPerformed
        if (jCheckBoxthreesymbols.isSelected()) {
            symbols = 3;
        }
        if (jCheckBoxfivesymbols.isSelected()) {
            symbols = 5;
        }
        jDialogstart.setVisible(false);
        jSliderchoicegamer.setMaximum(symbols - 1);
        jSliderchoicegamer.setMajorTickSpacing(1);
        jSliderchoicegamer.setMinorTickSpacing(1);
        jSliderchoicegamer.setValue(0);
        jLabelnamegamer.setBackground(RockScissorsPaper.gamercolor);
        jLabelnamegamer.setText(RockScissorsPaper.namegamer);
        RockScissorsPaper.setNumround(trys);
        RockScissorsPaper.setSymbols(symbols);
    }//GEN-LAST:event_jButtonaceptstartActionPerformed

    private void jSliderchoicegamerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderchoicegamerMouseDragged
        jLabelselection.setText(RockScissorsPaper.toStringvalues(jSliderchoicegamer.getValue()));
    }//GEN-LAST:event_jSliderchoicegamerMouseDragged


    private void jButtongameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtongameActionPerformed

        if (RockScissorsPaper.getNumround() > 0) {
            RockScissorsPaper.setComputer();
            RockScissorsPaper.setGamer(jSliderchoicegamer.getValue());
            RockScissorsPaper.whoIsWinner();
            jLabelchoiceimagePC.setIcon(this.getImage(RockScissorsPaper.getMovecomputer()));
            jLabelchoiceimagegamer.setIcon(this.getImage(RockScissorsPaper.getMovegamer()));
            this.repaint();
            JOptionPane.showMessageDialog(this, RockScissorsPaper.getWinnerString(),
                    RockScissorsPaper.toStringround(), JOptionPane.INFORMATION_MESSAGE);
            jProgressBar1.setValue(jProgressBar1.getValue()
                    + (jProgressBar1.getMaximum() / trys));
            jTextFieldscoregamer.setText(String.valueOf(RockScissorsPaper.getScoregamer()));
            jTextFieldscorepc.setText(String.valueOf(RockScissorsPaper.getScorecomputer()));
            jSliderchoicegamer.setValue(0);
            if (RockScissorsPaper.getNumround() == 0) {
                JOptionPane.showMessageDialog(this, "The Winner is "
                        + RockScissorsPaper.getWinnerRound(), "Cogratulations",
                        JOptionPane.INFORMATION_MESSAGE);
                jLabelchoiceimagePC.setIcon(this.getImage(RockScissorsPaper.getMovecomputer()));
                jLabelchoiceimagePC.repaint();
                jLabelchoiceimagegamer.setIcon(this.getImage(RockScissorsPaper.getMovegamer()));
                jLabelchoiceimagegamer.repaint();
                jButtongame.setEnabled(false);
                jSliderchoicegamer.setValue(0);
            }
        }

    }//GEN-LAST:event_jButtongameActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        jButtongame.setEnabled(true);
        jTextFieldscoregamer.setText("");
        jTextFieldscoregamer.setText("");
        RockScissorsPaper.setDefault(trys);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItemsettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemsettingActionPerformed

        jDialogsettings.setVisible(true);
        jDialogsettings.setAlwaysOnTop(true);
        jDialogname.setLocationRelativeTo(jDialogsettings);
        jDialogColor.setLocationRelativeTo(jDialogsettings);
        jSlidertrys.setValue(RockScissorsPaper.numround);
        jTextFieldtrys.setText(String.valueOf(RockScissorsPaper.numround));
        jLabelname.setText(RockScissorsPaper.namegamer);
        jTextFieldname.setText(RockScissorsPaper.namegamer);
        jPanelcolor.setBackground(RockScissorsPaper.gamercolor);
        switch (theme) {
            case 0:
                jRadioButtontheme1.setSelected(true);
                break;
            case 1:
                jRadioButtontheme2.setSelected(true);
                break;
            case 2:
                jRadioButtontheme3.setSelected(true);
                break;
            case 3:
                jRadioButtontheme4.setSelected(true);
                break;
            case 4:
                jRadioButtontheme5.setSelected(true);
                break;
            case 5:
                jRadioButtontheme6.setSelected(true);
                break;
            default:
                jRadioButtontheme1.setSelected(true);
        }

        switch (RockScissorsPaper.symbols) {
            case 3:
                jComboBox1.setSelectedIndex(0);
                break;
            case 5:
                jComboBox1.setSelectedIndex(1);
                break;
            default:
                jComboBox1.setSelectedIndex(10);
        }


    }//GEN-LAST:event_jMenuItemsettingActionPerformed

    private void jSliderchoicegamerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSliderchoicegamerKeyTyped
        jLabelselection.setText(RockScissorsPaper.toStringvalues(jSliderchoicegamer.getValue()));
    }//GEN-LAST:event_jSliderchoicegamerKeyTyped

    private void jButtonacepsettingAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButtonacepsettingAncestorAdded

    }//GEN-LAST:event_jButtonacepsettingAncestorAdded

    private void jButtonacepsettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonacepsettingActionPerformed
        RockScissorsPaper.setNumround(jSlidertrys.getValue());
        jLabelnamegamer.setText(RockScissorsPaper.namegamer);
        jLabelnamegamer.setBackground(RockScissorsPaper.gamercolor);
        this.trys = RockScissorsPaper.numround;
        this.jMenuItemnewplayActionPerformed(evt);
        jDialogsettings.setVisible(false);

    }//GEN-LAST:event_jButtonacepsettingActionPerformed

    private void jSlidertrysMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlidertrysMouseReleased
        jTextFieldtrys.setText(String.valueOf(jSlidertrys.getValue()));
    }//GEN-LAST:event_jSlidertrysMouseReleased

    private void jTextFieldtrysKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldtrysKeyTyped
        jSlidertrys.setValue(Integer.valueOf(jTextFieldtrys.getText()));
    }//GEN-LAST:event_jTextFieldtrysKeyTyped

    private void jRadioButtontheme1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtontheme1ActionPerformed
        juegopiedrapapeltijeras.main.theme = 0;
        this.setTheme();
    }//GEN-LAST:event_jRadioButtontheme1ActionPerformed

    private void jRadioButtontheme2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtontheme2ActionPerformed
        juegopiedrapapeltijeras.main.theme = 1;
        this.setTheme();
    }//GEN-LAST:event_jRadioButtontheme2ActionPerformed

    private void jRadioButtontheme3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtontheme3ActionPerformed
        juegopiedrapapeltijeras.main.theme = 2;
        this.setTheme();
    }//GEN-LAST:event_jRadioButtontheme3ActionPerformed

    private void jRadioButtontheme4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtontheme4ActionPerformed
        juegopiedrapapeltijeras.main.theme = 3;
        this.setTheme();
    }//GEN-LAST:event_jRadioButtontheme4ActionPerformed

    private void jRadioButtontheme5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtontheme5ActionPerformed
        juegopiedrapapeltijeras.main.theme = 4;
        this.setTheme();
    }//GEN-LAST:event_jRadioButtontheme5ActionPerformed

    private void jRadioButtontheme6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtontheme6ActionPerformed
        juegopiedrapapeltijeras.main.theme = 5;
        this.setTheme();
    }//GEN-LAST:event_jRadioButtontheme6ActionPerformed

    private void jButtoncolor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncolor1ActionPerformed
        jDialogColor.setVisible(true);
        jDialogColor.setAlwaysOnTop(true);
        getRootPane().setDefaultButton(jButtonaceptcolor);
    }//GEN-LAST:event_jButtoncolor1ActionPerformed

    private void jButtonnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnameActionPerformed
        jDialogname.setVisible(true);
        jDialogColor.setAlwaysOnTop(true);
        getRootPane().setDefaultButton(jButtonaceptname);
    }//GEN-LAST:event_jButtonnameActionPerformed

    private void jButtoncancelsettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncancelsettingActionPerformed

        jDialogsettings.setVisible(false);
    }//GEN-LAST:event_jButtoncancelsettingActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        int auxs;
        switch (jComboBox1.getSelectedIndex()) {
            case 0:
                auxs = 3;
                RockScissorsPaper.setSymbols(auxs);
                symbols = auxs;
                jSliderchoicegamer.setMaximum(symbols - 1);
                break;
            case 1:
                auxs = 5;
                RockScissorsPaper.setSymbols(auxs);
                symbols = auxs;
                jSliderchoicegamer.setMaximum(symbols - 1);
                break;
            default:
                auxs = 3;
                RockScissorsPaper.setSymbols(auxs);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextFieldtrysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldtrysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldtrysActionPerformed
    private ImageIcon getImage(int Image) {
        switch (Image) {
            case 0:
                return ROCK;
            case 1:
                return PAPER;
            case 2:
                return SCISSORS;
            case 3:
                return LIZARD;
            case 4:
                return SPOCK;
            default:
                return DEFAULT;

        }
    }

    public void setTheme() {
        switch (theme) {
            case 0:
                jLabeltheme.setIcon(THEME);
                break;
            case 1:
                jLabeltheme.setIcon(THEME1);
                break;
            case 2:
                jLabeltheme.setIcon(THEME2);
                break;
            case 3:
                jLabeltheme.setIcon(THEME3);
                break;
            case 4:
                jLabeltheme.setIcon(THEME4);
                break;
            case 5:
                jLabeltheme.setIcon(THEME5);
                break;
            default:
                jLabeltheme.setIcon(THEME);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGrouplanguaje;
    private javax.swing.ButtonGroup buttonGroupsymbols;
    private javax.swing.ButtonGroup buttonGrouptheme;
    private javax.swing.JButton jButtonacepsetting;
    private javax.swing.JButton jButtonaceptcolor;
    private javax.swing.JButton jButtonaceptname;
    private javax.swing.JButton jButtonaceptstart;
    private javax.swing.JButton jButtoncancelsetting;
    private javax.swing.JButton jButtoncolor;
    private javax.swing.JButton jButtoncolor1;
    private javax.swing.JButton jButtongame;
    private javax.swing.JButton jButtonname;
    private javax.swing.JButton jButtonnombre;
    private javax.swing.JCheckBox jCheckBoxfivesymbols;
    private javax.swing.JCheckBox jCheckBoxthreesymbols;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDialog jDialogColor;
    private javax.swing.JDialog jDialogname;
    private javax.swing.JDialog jDialogsettings;
    private javax.swing.JDialog jDialogstart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelchoiceimagePC;
    private javax.swing.JLabel jLabelchoiceimagegamer;
    private javax.swing.JLabel jLabelname;
    private javax.swing.JLabel jLabelnamegamer;
    private javax.swing.JLabel jLabelselection;
    private javax.swing.JLabel jLabeltheme;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemexit;
    private javax.swing.JMenuItem jMenuItemnewplay;
    private javax.swing.JMenuItem jMenuItemresume;
    private javax.swing.JMenuItem jMenuItemsetting;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelcolor;
    private javax.swing.JPanel jPanelcolorgame;
    private javax.swing.JPanel jPanelcomputadora;
    private javax.swing.JPanel jPanelcustomize;
    private javax.swing.JPanel jPaneljugador;
    private javax.swing.JPanel jPanellanguage;
    private javax.swing.JPanel jPanelparameter;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButtondeutch;
    private javax.swing.JRadioButton jRadioButtonenglish;
    private javax.swing.JRadioButton jRadioButtonfrench;
    private javax.swing.JRadioButton jRadioButtonspanish;
    private javax.swing.JRadioButton jRadioButtontheme1;
    private javax.swing.JRadioButton jRadioButtontheme2;
    private javax.swing.JRadioButton jRadioButtontheme3;
    private javax.swing.JRadioButton jRadioButtontheme4;
    private javax.swing.JRadioButton jRadioButtontheme5;
    private javax.swing.JRadioButton jRadioButtontheme6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSliderchoicegamer;
    private javax.swing.JSlider jSlidertrys;
    private javax.swing.JTabbedPane jTabbedPanesetting;
    private javax.swing.JTextField jTextFieldname;
    private javax.swing.JTextField jTextFieldscoregamer;
    private javax.swing.JTextField jTextFieldscorepc;
    private javax.swing.JTextField jTextFieldtrys;
    // End of variables declaration//GEN-END:variables
}
