/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EsteLavajillas;

/**
 *
 * @author Manuel Manzano López
 */
public class main extends javax.swing.JFrame {

    Lavavajillas Lavavajillas1= new Lavavajillas();
    public void getStatus(){
        jTextFieldPuerta.setText(Lavavajillas1.getStatusdoor());
        jTextFieldEnergia.setText(Lavavajillas1.getStatuspower());
        jTextFieldPrograma.setText(Lavavajillas1.getStatusprogramString());
    }
    public void setDoor(boolean estado){
        Lavavajillas1.setStatusdoor(estado);
    }
    public void setPower(boolean estado){
        Lavavajillas1.setStatuspower(estado);
    }
    public void setStatus(int estado){
        Lavavajillas1.setStatusProgramManual(estado);
    }
    public void setStatus(){
        Lavavajillas1.setStatusProgramAuto();
    }
    
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAbrirPuerta = new javax.swing.JButton();
        jTextFieldPuerta = new javax.swing.JTextField();
        jTextFieldEnergia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonEnjuagado = new javax.swing.JButton();
        jButtonCerrarpuerta = new javax.swing.JButton();
        jButtonEncender = new javax.swing.JButton();
        jButtonApagar = new javax.swing.JButton();
        jButtonLavado = new javax.swing.JButton();
        jButtonPrelavado = new javax.swing.JButton();
        jButtonAclarado = new javax.swing.JButton();
        jButtonSecado = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPrograma = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonAbrirPuerta.setText("Abrir puerta");
        jButtonAbrirPuerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirPuertaActionPerformed(evt);
            }
        });

        jTextFieldPuerta.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextFieldEnergia.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel1.setText("Puerta:");

        jLabel2.setText("Energía:");

        jButtonEnjuagado.setText("Enjuagado");
        jButtonEnjuagado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnjuagadoActionPerformed(evt);
            }
        });

        jButtonCerrarpuerta.setText("Cerrar puerta");
        jButtonCerrarpuerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarpuertaActionPerformed(evt);
            }
        });

        jButtonEncender.setText("Encender");
        jButtonEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncenderActionPerformed(evt);
            }
        });

        jButtonApagar.setText("Apagar");
        jButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarActionPerformed(evt);
            }
        });

        jButtonLavado.setText("Lavado");
        jButtonLavado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLavadoActionPerformed(evt);
            }
        });

        jButtonPrelavado.setText("Prelavado");
        jButtonPrelavado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrelavadoActionPerformed(evt);
            }
        });

        jButtonAclarado.setText("Aclarado");
        jButtonAclarado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAclaradoActionPerformed(evt);
            }
        });

        jButtonSecado.setText("Secado");
        jButtonSecado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSecadoActionPerformed(evt);
            }
        });

        jButton2.setText("Avanzar el programa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Programa :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextFieldEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonEnjuagado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPrelavado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonLavado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAclarado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSecado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButtonAbrirPuerta)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCerrarpuerta)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEncender)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonApagar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldPrograma)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAbrirPuerta)
                    .addComponent(jButtonCerrarpuerta)
                    .addComponent(jButtonEncender)
                    .addComponent(jButtonApagar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEnjuagado)
                    .addComponent(jButtonPrelavado)
                    .addComponent(jButtonAclarado)
                    .addComponent(jButtonLavado)
                    .addComponent(jButtonSecado))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAbrirPuertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirPuertaActionPerformed

        setDoor(true);
        getStatus();
    }//GEN-LAST:event_jButtonAbrirPuertaActionPerformed

    private void jButtonCerrarpuertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarpuertaActionPerformed
        setDoor(false);
        getStatus();
    }//GEN-LAST:event_jButtonCerrarpuertaActionPerformed

    private void jButtonEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncenderActionPerformed
        setPower(false);
        getStatus();
    }//GEN-LAST:event_jButtonEncenderActionPerformed

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed
        setPower(true);
        getStatus();
    }//GEN-LAST:event_jButtonApagarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setStatus();
        getStatus();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonEnjuagadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnjuagadoActionPerformed
        setStatus(1);
        getStatus();
        
    }//GEN-LAST:event_jButtonEnjuagadoActionPerformed

    private void jButtonPrelavadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrelavadoActionPerformed
        setStatus(2);
        getStatus();
    }//GEN-LAST:event_jButtonPrelavadoActionPerformed

    private void jButtonLavadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLavadoActionPerformed
        setStatus(3);
        getStatus();
    }//GEN-LAST:event_jButtonLavadoActionPerformed

    private void jButtonAclaradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAclaradoActionPerformed
       setStatus(4);
       getStatus();
    }//GEN-LAST:event_jButtonAclaradoActionPerformed

    private void jButtonSecadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSecadoActionPerformed
       setStatus(5);
       getStatus();
    }//GEN-LAST:event_jButtonSecadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAbrirPuerta;
    private javax.swing.JButton jButtonAclarado;
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonCerrarpuerta;
    private javax.swing.JButton jButtonEncender;
    private javax.swing.JButton jButtonEnjuagado;
    private javax.swing.JButton jButtonLavado;
    private javax.swing.JButton jButtonPrelavado;
    private javax.swing.JButton jButtonSecado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldEnergia;
    private javax.swing.JTextField jTextFieldPrograma;
    private javax.swing.JTextField jTextFieldPuerta;
    // End of variables declaration//GEN-END:variables
}
