/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clasereloj;

/**
 *
 * @author Manuel Manzano López
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButtondamehora = new javax.swing.JButton();
        jTextFieldresultado = new javax.swing.JTextField();
        jTextFieldhoras = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonhoraactual = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldminutos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldsegundos = new javax.swing.JTextField();
        jRadioButton24horas = new javax.swing.JRadioButton();
        jRadioButtonAMPM = new javax.swing.JRadioButton();
        jButton1quehoraes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtondamehora.setText("Dame Hora");
        jButtondamehora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondamehoraActionPerformed(evt);
            }
        });

        jTextFieldresultado.setEditable(false);
        jTextFieldresultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextFieldhoras.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButtonhoraactual.setText("Hora Actual");
        jButtonhoraactual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonhoraactualActionPerformed(evt);
            }
        });

        jLabel2.setText("Horas:");

        jTextFieldminutos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel3.setText("Minutos:");

        jLabel4.setText("Segundos:");

        jTextFieldsegundos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        buttonGroup1.add(jRadioButton24horas);
        jRadioButton24horas.setSelected(true);
        jRadioButton24horas.setText("24H");
        jRadioButton24horas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton24horasActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonAMPM);
        jRadioButtonAMPM.setText("AM/PM");

        jButton1quehoraes.setText("Que hora");
        jButton1quehoraes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1quehoraesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextFieldhoras, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldminutos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextFieldsegundos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jRadioButton24horas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonAMPM))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextFieldresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1quehoraes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtondamehora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonhoraactual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldhoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldminutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldsegundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButton1quehoraes, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonhoraactual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtondamehora)
                    .addComponent(jTextFieldresultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton24horas)
                    .addComponent(jRadioButtonAMPM))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtondamehoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondamehoraActionPerformed
       
        Reloj reloj1= new Reloj(Byte.valueOf(jTextFieldhoras.getText()), 
                Byte.valueOf(jTextFieldminutos.getText()), 
                Byte.valueOf(jTextFieldsegundos.getText()));
        if(jRadioButton24horas.isSelected()){
            
            jTextFieldresultado.setText(reloj1.getFormatohora(true));
        }else{
            jTextFieldresultado.setText(reloj1.getFormatohora(false));
        }
    }//GEN-LAST:event_jButtondamehoraActionPerformed

    private void jButtonhoraactualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonhoraactualActionPerformed
        
        Reloj reloj2 = new Reloj();
        reloj2.ponerEnHoras();
        if(jRadioButton24horas.isSelected()){
            
            jTextFieldresultado.setText(reloj2.getFormatohora(true));
        }else{
            jTextFieldresultado.setText(reloj2.getFormatohora(false));
        }
       
    }//GEN-LAST:event_jButtonhoraactualActionPerformed

    private void jRadioButton24horasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton24horasActionPerformed
        
    }//GEN-LAST:event_jRadioButton24horasActionPerformed

    private void jButton1quehoraesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1quehoraesActionPerformed
 
        Reloj reloj1= new Reloj(Byte.valueOf(jTextFieldhoras.getText()), 
                Byte.valueOf(jTextFieldminutos.getText()), 
                Byte.valueOf(jTextFieldsegundos.getText()));
        
        if(reloj1.getFormatohora()){
            jRadioButtonAMPM.setSelected(false);
            jRadioButton24horas.setSelected(true);
        }else{
            jRadioButtonAMPM.setSelected(true);
            jRadioButton24horas.setSelected(false);
            
        }
        
    }//GEN-LAST:event_jButton1quehoraesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1quehoraes;
    private javax.swing.JButton jButtondamehora;
    private javax.swing.JButton jButtonhoraactual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton24horas;
    private javax.swing.JRadioButton jRadioButtonAMPM;
    private javax.swing.JTextField jTextFieldhoras;
    private javax.swing.JTextField jTextFieldminutos;
    private javax.swing.JTextField jTextFieldresultado;
    private javax.swing.JTextField jTextFieldsegundos;
    // End of variables declaration//GEN-END:variables
}
